version: '3.8'

services:
  biothings-studio-webapp:
    build:
      context: .
      dockerfile: Dockerfile.webapp
    container_name: biothings_studio_webapp
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - nginx:/logs/data/nginx

  biothings:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BIOTHINGS_VERSION=master
        - BIOTHINGS_REPOSITORY=https://github.com/biothings/biothings.api.git
        - ES_HOST=elasticsearch
        - MONGO_HOST=mongo
        - PROD=1
    container_name: biothings
    restart: unless-stopped
    ports:
      - 22:22
      - 7022:7022 # hub ssh
      - 7080:7080 # hub api

  elasticsearch:
    image: elasticsearch:8.8.1
    container_name: elasticsearch
    restart: unless-stopped
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - cluster.name=biothings
      - discovery.type=single-node
      - xpack.security.enabled=false
      # - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # uncomment to change ES heap size
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 32000
        hard: 65536
    volumes:
      - esdata:/usr/share/elasticsearch/data

  cerebro:
    build:
      context: .
      dockerfile: Dockerfile.cerebro
      args: 
        - ES_HOST=elasticsearch
    container_name: cerebro
    restart: unless-stopped
    ports:
      - 9000:9000

  mongo:
    build:
      context: .
      dockerfile: Dockerfile.mongo
    container_name: mongo
    restart: unless-stopped
    ports: 
      - 27017:27017
    volumes:
      - mongo:/data/mongodb
      - mongologs:/data/logs/mongodb


volumes:
  nginx:
  esdata:
  mongo:
  mongologs: