FROM ghcr.io/lmenezes/cerebro-docker:latest

USER root

ARG ES_HOST

# Add biothings studio to hosts
RUN sed -i "/^hosts = \\[$/a \
  { \
    host = \"http://${ES_HOST}:9200\", \
    \"name\" = \"BioThings Studio\" \
  }" /opt/cerebro/conf/application.conf && \
  cat /opt/cerebro/conf/application.conf

EXPOSE 9000