###################################################
# Setup home directory, biothings app codebase
###################################################

- name: bashrc
  lineinfile: path=/home/biothings/.bashrc line='source $HOME/pyenv/bin/activate'
  become_user: "biothings"
  become: true

- name: pythonpath
  lineinfile: path=/home/biothings/.bashrc line='export PYTHONPATH=.:$PYTHONPATH'
  become_user: "biothings"
  become: true

- name: locale
  lineinfile: path=/home/biothings/.bashrc line='export LC_ALL=C.UTF-8'
  become_user: "biothings"
  become: true

# Logs folder
- name: logs directory
  file: path=/data/logs state=directory
- name: supervisor logs directory
  file: path=/data/logs/supervisor state=directory owner=www-data group=www-data
# studio/api folder
- name: app data directory
  file: path=/data/{{ app_name }} state=directory owner=biothings group=biothings
- name: data plugins directory
  file: path=/data/{{ app_name }}/plugins state=directory owner=biothings group=biothings
- name: data sources directory
  file: path=/data/{{ app_name }}/datasources state=directory owner=biothings group=biothings
- name: data upload directory
  file: path=/data/{{ app_name }}/dataupload state=directory owner=biothings group=biothings
# misc
- name: run directory
  file: path=/data/run state=directory owner=biothings group=biothings
- name: conf directory
  file: path=/data/conf state=directory

#- debug: var=software.web_node

- name: biothings (override requirement_web.txt version)
  git: repo={{ software.web_node.biothings_repository }} dest=/home/biothings/biothings.api version={{ software.web_node.biothings_git_version }}
  become_user: "biothings"
  become: true

- name: Install biothings lib requirements into virtualenv
  shell: "source $HOME/pyenv/bin/activate && pip install .[hub]"
  args:
    executable: /bin/bash
    chdir: /home/biothings/biothings.api
  become_user: "biothings"
  become: true

- name: biothings api as subfolder
  file: src=/home/biothings/biothings.api/biothings dest=/home/biothings/{{ app_name }}/biothings state=link
  become_user: "biothings"
  become: true

- name: pretty mongo shell
  lineinfile: dest=/home/biothings/.mongorc.js line="DBQuery.prototype._prettyShell = true" mode=0644 owner=biothings group=biothings insertafter=EOF create=yes

- name: Inject docker mongo uri into config.py
  lineinfile: dest=/home/biothings/biothings_studio/config.py line="{{ item.line }}" insertbefore=EOF
  with_items:
    - {"line":"HUB_DB_BACKEND['uri'] = 'mongodb://{{ software.common_configurations.mongodb.host }}'"} # mongodb url for mongo docker container: have to point to mongo instead of localhost
    - {"line":"DATA_SRC_SERVER = '{{ software.common_configurations.mongodb.host }}'"} 
    - {"line":"DATA_TARGET_SERVER = '{{ software.common_configurations.mongodb.host }}'"} 

- name: Inject docker elasticsearch uri into config.py
  lineinfile: dest=/home/biothings/biothings_studio/config.py line="{{ item.line }}" insertbefore=EOF
  with_items:
    - {"line":"from contextlib import suppress"}
    - {"line":"with suppress(NameError): STANDALONE_CONFIG['_default']['es_host'] = '{{ software.common_configurations.elasticsearch.host }}:9200'"} 
    - {"line":"INDEX_CONFIG['env'].setdefault('localhub', {})['host'] = '{{ software.common_configurations.elasticsearch.host }}:9200'"}
    - {"line":"INDEX_CONFIG['env'].setdefault('local', {})['host'] = '{{ software.common_configurations.elasticsearch.host }}:9200'"}

- name: Inject docker elasticsearch uri into config.py
  lineinfile: dest=/home/biothings/biothings.api/biothings/web/settings/default.py line="{{ item.line }}" insertbefore=EOF
  with_items:
    - {"line":"ES_HOST = '{{ software.common_configurations.elasticsearch.host }}:9200'"}

- name: Template out docker entry point
  template: mode=0755 src=templates/docker-entrypoint.sh dest=/docker-entrypoint.sh
- name: home bin
  file: path=/home/biothings/bin state=directory owner=biothings group=biothings
- name: Template out update_biothings
  template: mode=0755 src=templates/update_biothings dest=/home/biothings/bin/update_biothings
- name: Template out run_studio
  template: mode=0755 src=templates/run_studio dest=/home/biothings/bin/run_studio
- name: Template out show_help_msg
  template: mode=0755 src=templates/show_help_msg dest=/home/biothings/bin/show_help_msg
