#####################################################################
# Update security/limits.conf
#####################################################################

- name: Update /etc/security/limits.conf
  lineinfile: dest=/etc/security/limits.conf insertbefore="^# End of file" line="{{ item.line }}" mode=0644 owner=root group=root
  become: yes
  with_items:
    - {"line":"elasticsearch soft nofile {{ software.common_configurations.elasticsearch.soft_file_limit }}"}
    - {"line":"elasticsearch hard nofile {{ software.common_configurations.elasticsearch.hard_file_limit }}"}

###################
# Install Cerebro #
###################

- name: Configure Cerebro
  lineinfile: dest=/usr/local/cerebro/conf/application.conf line="{{ item }}" mode=0644 owner=root group=root insertafter="^hosts ="
  with_items:
    - '},'
    - '  name = "BioThings Studio"'
    - '  host = "http://localhost:9200"'
    - '{'

- name: make sure Cerebro (make sure what??)
  file:
    path: /usr/local/cerebro
    owner: elasticsearch

##################################################
# Install nginx
##################################################

- name: Template out nginx.conf to server
  template: src=templates/nginx.conf dest=/etc/nginx/nginx.conf owner=root group=root mode=0644
  become: yes

- name: nginx logs directory
  file: path=/data/logs/nginx state=directory owner=www-data group=www-data

###################################################
## Install elasticsearch
###################################################
#
#- name: Template out elasticsearch.yml to server
#  template: src=templates/elasticsearch.yml dest=/etc/elasticsearch/elasticsearch.yml owner=root group=root mode=0644
#  become: yes
#
#- name: elasticsearch logs directory
#  file: path=/data/logs/elasticsearch state=directory owner=elasticsearch group=elasticsearch

###################################################
# Setup home directory, biothings app codebase
###################################################

- name: bashrc
  lineinfile: path=/home/biothings/.bashrc line='source $HOME/pyenv/bin/activate'
  become_user: "biothings"
  become: true

- name: pythonpath
  lineinfile: path=/home/biothings/.bashrc line='export PYTHONPATH=.:$PYTHONPATH'
  become_user: "biothings"
  become: true

- name: locale
  lineinfile: path=/home/biothings/.bashrc line='export LC_ALL=C.UTF-8'
  become_user: "biothings"
  become: true

# Logs folder
- name: logs directory
  file: path=/data/logs state=directory
- name: nginx logs directory
  file: path=/data/logs/nginx state=directory owner=www-data group=www-data
- name: supervisor logs directory
  file: path=/data/logs/supervisor state=directory owner=www-data group=www-data
- name: elasticsearch logs directory
  file: path=/data/logs/elasticsearch state=directory owner=elasticsearch group=elasticsearch
# studio/api folder
- name: app data directory
  file: path=/data/{{ app_name }} state=directory owner=biothings group=biothings
- name: data plugins directory
  file: path=/data/{{ app_name }}/plugins state=directory owner=biothings group=biothings
- name: data sources directory
  file: path=/data/{{ app_name }}/datasources state=directory owner=biothings group=biothings
- name: data upload directory
  file: path=/data/{{ app_name }}/dataupload state=directory owner=biothings group=biothings
# misc
- name: run directory
  file: path=/data/run state=directory owner=biothings group=biothings
- name: conf directory
  file: path=/data/conf state=directory
# database data folders
- name: elasticsearch data directory
  file: path=/data/elasticsearch state=directory owner=elasticsearch group=elasticsearch

#- debug: var=software.web_node

- name: biothings (override requirement_web.txt version)
  git: repo={{ software.web_node.biothings_repository }} dest=/home/biothings/biothings.api version={{ software.web_node.biothings_git_version }}
  become_user: "biothings"
  become: true

- name: Install biothings lib requirements into virtualenv
  shell: "source $HOME/pyenv/bin/activate && pip install .[hub]"
  args:
    executable: /bin/bash
    chdir: /home/biothings/biothings.api
  become_user: "biothings"
  become: true

- name: biothings api as subfolder
  file: src=/home/biothings/biothings.api/biothings dest=/home/biothings/{{ app_name }}/biothings state=link
  become_user: "biothings"
  become: true

- name: pretty mongo shell
  lineinfile: dest=/home/biothings/.mongorc.js line="DBQuery.prototype._prettyShell = true" mode=0644 owner=biothings group=biothings insertafter=EOF create=yes

- name: Inject docker mongo uri into config.py
  lineinfile: dest=/home/biothings/biothings_studio/config.py line="{{ item.line }}" insertbefore=EOF
  with_items:
    - {"line":"HUB_DB_BACKEND['uri'] = 'mongodb://mongo'"} # mongodb url for mongo container: have to point to mongo instead of localhost
    - {"line":"DATA_SRC_SERVER = 'mongo'"} 
    - {"line":"DATA_TARGET_SERVER = 'mongo'"} 

- name: Template out docker entry point
  template: mode=0755 src=templates/docker-entrypoint.sh dest=/docker-entrypoint.sh
- name: home bin
  file: path=/home/biothings/bin state=directory owner=biothings group=biothings
- name: Template out update_biothings
  template: mode=0755 src=templates/update_biothings dest=/home/biothings/bin/update_biothings
- name: Template out run_studio
  template: mode=0755 src=templates/run_studio dest=/home/biothings/bin/run_studio
- name: Template out show_help_msg
  template: mode=0755 src=templates/show_help_msg dest=/home/biothings/bin/show_help_msg

################################################
# Update elasticsearch.yml
################################################

- name: es backups data directory (repo type fs)
  file: path=/data/es_backups mode=0777 state=directory owner=elasticsearch group=elasticsearch

- name: Update elasticsearch.yml file
  lineinfile: dest=/etc/elasticsearch/elasticsearch.yml line="{{ item }}" mode=0644 owner=root group=root insertafter=EOF
  become: yes
  with_items:
    - "#######"
    - "cluster.name: {{ cluster.name }}"
    - "node.roles: {{ software.web_node.elasticsearch.node_roles }}"
    - "{{ software.common_configurations.elasticsearch.elasticsearch_yml }}"
    # this will avoid to have max virtual memory areas vm.max_map_count [65530] likely too low
    # (not suitable for production with a cluster)
    - "discovery.type: single-node"
    - 'path.repo: ["/data/es_backups"]'
    - "ingest.geoip.downloader.enabled: false"

- name: update elasticsearch.yml again replacing some values
  replace: dest=/etc/elasticsearch/elasticsearch.yml replace="{{ item.line }}" regexp="{{ item.re }}"
  become: yes
  with_items:
    - {"line": "path.data: /data/elasticsearch", "re": "^path.data.*$"}
    - {"line": "path.logs: /data/logs/elasticsearch", "re": "^path.logs.*$"}
    - {"line": "", "re": "^cluster.initial_master_nodes.*$"}
    - {"line": "xpack.security.enabled: false", "re": "^xpack.security.enabled.*$"}


- name: Update /etc/elasticsearch/jvm.options.d/heap.options again replacing min/max heap size
  when: software.web_node.elasticsearch.heap_size != ''
  shell:
    cmd: |
      cat > /etc/elasticsearch/jvm.options.d/heap.options << EOF
      -Xms{{ software.web_node.elasticsearch.heap_size }}
      -Xmx{{ software.web_node.elasticsearch.heap_size }}
      EOF
  args:
    executable: /bin/sh
