version: "3.3"

services:
    biothings.data:
        # The dash in the container name is used for a valid hostname
        container_name: "biothings-data"
        image: "biothings.data"
        networks:
            - biothings

    mongodb:
        container_name: "mongodb"
        image: "mongo:3.2"
        networks:
            - biothings

    elasticsearch:
        container_name: "elasticsearch"
        image: "docker.elastic.co/elasticsearch/elasticsearch:5.6.4"
        networks:
            - biothings

    biothings.interactions:
        container_name: "biothings.interactions"
        image: "biothings.interactions"
        ports:
            - "8022:8022"

        networks:
            - biothings

networks:
    biothings:
