version: "3.3"

services:
    mongodb:
        container_name: "mongodb"
        image: "mongo:3.2"
        networks:
            - biothings

    elasticsearch:
        container_name: "elasticsearch"
        image: "docker.elastic.co/elasticsearch/elasticsearch:5.6.4"
        networks:
            - biothings

    mychem.info:
        container_name: "mychem.info"
        image: "mychem.info"
        ports:
            - 8022:8022
        networks:
            - biothings

networks:
    biothings:

