---

app_name: "biothings_studio"

# Variables relating to the whole cluster
cluster:
  name: biothings
  environment: studio

software:
  web_node:
    biothings_repository: "{{ biothings_repository | default('https://github.com/biothings/biothings.api.git', true) }}"
    biothings_git_version: "{{ biothings_version | default('master')}}"
  common_configurations:
    elasticsearch:
      host: "{{ es_host | default('elasticsearch') }}"
    mongodb:
      host: "{{ mongo_host | default('mongo') }}"
